import { Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const sora = Sora({ 
  subsets: ["latin"],
  weight :['300','400','500','600','700'],
  style:'normal',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="dark">
      <body className={`dark:bg-body bg-white font-[Sora] dark:text-white text-dark ${sora.className}`}>
        <Header />
        {children}
          <div id="modal-root"></div>
        <Footer />
      </body>
    </html>
  );
}
